version: "3.9"
services:
  quotes:
    image: npizzo/backend-prod:1.1
    entrypoint: /src/server-entrypoint.sh
    volumes:
      - static_volue:/src/backend/django_static
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=$DEBUG
      - QUOTES_API_KEY=$QUOTES_API_KEY
      - TWILIO_API_KEY=$TWILIO_API_KEY
      - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_HOST_USER=$EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
  worker:
    image: npizzo/backend-prod:1.1
    entrypoint: /src/worker-entrypoint.sh
    volumes:
      - static_volue:/src/backend/django_static
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=$DEBUG
      - QUOTES_API_KEY=$QUOTES_API_KEY
      - TWILIO_API_KEY=$TWILIO_API_KEY
      - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_HOST_USER=$EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
    depends_on:
      - quotes
      - redis
  nginx:
    image: npizzo/webserver-prod:1.1
    restart: always
    ports:
      - "80:80"
  redis:
    image: redis

volumes:
  static_volue: {}