version: "3.9"
services:
  quotes:
    image: npizzo/backend-prod:postgres
    entrypoint: /src/server-entrypoint.sh
    volumes:
      - static_volue:/src/backend/django_sqlite
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=$DEBUG
      - QUOTES_API_KEY=$QUOTES_API_KEY
      - TWILIO_API_KEY=$TWILIO_API_KEY
      - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_HOST_USER=$EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
    depends_on:
      - db
  worker:
    image: npizzo/backend-prod:postgres
    entrypoint: /src/worker-entrypoint.sh
    volumes:
      - static_volue:/src/backend/django_sqlite
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=$DEBUG
      - QUOTES_API_KEY=$QUOTES_API_KEY
      - TWILIO_API_KEY=$TWILIO_API_KEY
      - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_HOST_USER=$EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
    depends_on:
      - quotes
      - redis
  nginx:
    image: npizzo/webserver-prod:postgres
    restart: always
    ports:
      - "80:80"
  redis:
    image: redis
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  static_volue: {}
  postgres_data: